const translations = {
    en: {
        title: "SpeedAir - Your Trusted Travel Partner",
        brand: "SpeedAir",
        about_us_nav: "About us",
        services_nav: "Services",
        reviews_nav: "Reviews",
        contact_nav: "Contact & Support",
        welcome: "Welcome to SpeedAir",
        welcome_sub: "Your journey begins with us",
        iata_title: "IATA Accredited Agent",
        iata_desc: "Recognized by the International Air Transport Association for excellence in travel services and compliance.",
        top_seller_title: "Top Seller Award 2024",
        top_seller_desc: "Honored as a top seller by leading airlines for outstanding ticket sales and customer satisfaction.",
        global_member_title: "Global Travel Network Member",
        global_member_desc: "Part of a worldwide network of trusted travel agencies, ensuring quality and reliability for our clients.",
        why_book: "Why Book With SpeedAir?",
        why_book_desc: "Enjoy a seamless booking experience with instant confirmation, flexible options, and exclusive offers tailored for you. Our platform is designed for your convenience, allowing you to compare flights, manage your bookings, and access support anytime. Whether you’re planning a business trip or a family vacation, SpeedAir ensures you get the best value and service every step of the way.",
        agents: "Professional Agents",
        agents_desc: "Our dedicated team of travel experts is always ready to assist you with personalized service and expert advice.",
        customers: "Happy Customers",
        customers_desc: "Millions of travelers trust SpeedAir for their journeys, thanks to our commitment to satisfaction and reliability.",
        years: "Years of Excellence",
        years_desc: "Delivering quality travel solutions and building lasting relationships since our founding.",
        certificates_title: "Our Certificates & Achievements",
        benefits_title: "Our Benefits & Features",
        best_price: "Best Price Deals",
        best_price_desc: "We constantly monitor fares to bring you the lowest prices and exclusive discounts on flights worldwide.",
        live_support: "24/7 Live Support",
        live_support_desc: "Our support team is available around the clock to help you with bookings, changes, or any travel questions.",
        reliable_safe: "Reliable & Safe",
        reliable_safe_desc: "Your safety and privacy are our top priorities. We use secure technology and partner only with trusted airlines.",
        contact_us: "Contact Us",
        contact_us_desc: "Whether you have questions about our services, need support, or want to share your feedback, our dedicated team is here to assist you every step of the way.",
        email: "Email",
        website: "Website",
        phone: "Phone",
        location: "Location",
        get_in_touch: "Get in touch.",
        your_name: "Your Name",
        email_address: "Email Address",
        phone_number: "Phone Number",
        message: "Message",
        submit: "Submit",
        roundtrip: "Roundtrip",
        oneway: "One-way",
        depart_from: "Depart from",
        arrive_at: "Arrive at",
        traveller_toggle: "1 Adult, Economy",
        search: "Search",
        adult: "Adult 12+",
        child: "Child 2-11",
        infant: "Infant 0-1",
        swap: "Swap",
        decrease: "Decrease",
        increase: "Increase",
        footer: "© 2024 SpeedAir Travel Agency. All rights reserved.",
        // Add to each language in translations:
        who_is_speedair: "Who is SpeedAir",
        who_is_speedair_text: "SpeedAir is a leading travel agency dedicated to making your journeys seamless, memorable, and affordable. With years of experience in the travel industry, our passionate team is committed to providing personalized travel solutions for individuals, families, and businesses.",
        our_mission: "Our Mission",
        our_mission_text: "To inspire and enable people to explore the world by offering exceptional travel experiences, outstanding customer service, and unbeatable value.",
        our_values: "Our Values",
        customer_focus: "Customer Focus",
        customer_focus_text: "We put your needs first, ensuring every trip is tailored to your preferences.",
        reliability: "Reliability",
        reliability_text: "Count on us for transparent, hassle-free bookings and support at every step.",
        expertise: "Expertise",
        expertise_text: "Our experienced agents provide insider tips and the best travel deals worldwide.",
        why_choose: "Why Choose SpeedAir?",
        li1: "Wide range of domestic and international destinations",
        li2: "Customized travel packages",
        li3: "24/7 customer support",
        li4: "Competitive pricing and exclusive offers",
        li5: "Trusted by thousands of happy travelers",
        our_locations: "Our Locations",
        address: "Address",
        services_title: "Our Services",
        flight_bookings: "Flight Bookings",
        flight_bookings_desc: "Book domestic and international flights with the best deals and flexible options.",
        hotel_reservations: "Hotel Reservations",
        hotel_reservations_desc: "Choose from a wide range of hotels and accommodations to suit your needs and budget.",
        car_rentals: "Car Rentals",
        car_rentals_desc: "Rent cars at your destination for convenience and comfort during your travels.",
        travel_packages: "Travel Packages",
        travel_packages_desc: "Enjoy customized travel packages for families, couples, and solo adventurers.",
        travel_insurance: "Travel Insurance",
        travel_insurance_desc: "Travel with peace of mind with our comprehensive insurance options.",
        support_247: "24/7 Support",
        support_247_desc: "Our team is available around the clock to assist you before, during, and after your trip.",
        need_special: "Need Something Special?",
        ready_adventure: "Ready to plan your next adventure?",
        why_choose: "Why choose SpeedAir?",
        customer_say: "What Our Customers Say",
        review_1: "SpeedAir made our honeymoon unforgettable! The booking process was smooth and the staff was always available to help. Highly recommended!",
        review_2: "I was nervous about traveling abroad, but SpeedAir took care of everything. I felt safe and supported every step of the way.",
        review_3: "Great service and excellent value for money. Will definitely book my next trip with SpeedAir!",
        review_4: "Professional, reliable, and friendly. SpeedAir exceeded my expectations!",
        leave_review_heading: "Want to share your experience?",
        leave_review_text: "We value your feedback! Click below to leave a review or contact us for more information.",
        leave_review_button: "Leave a Review / Contact Us",
        contact_us: "Contact Us",
        contact_text: "Whether you have questions about our services, need support, or want to share your feedback, our dedicated team is here to assist you every step of the way.",
        email: "Email",
        website: "Website",
        phone: "Phone",
        location: "Location",
        get_in_touch: "Get in touch.",
        your_name: "Your Name",
        email_address: "Email Address",
        phone_number: "Phone Number",
        message: "Message",
        submit: "Submit",
        footer_text: "© 2025 SpeedAir Travel Agency. All rights reserved."
    },
    ru: {
        title: "SpeedAir - Ваш надежный партнер в путешествиях",
        brand: "SpeedAir",
        about_us_nav: "О нас",
        services_nav: "Услуги",
        reviews_nav: "Отзывы",
        contact_nav: "Контакты и поддержка",
        welcome: "Добро пожаловать в SpeedAir",
        welcome_sub: "Ваше путешествие начинается с нами",
        iata_title: "Аккредитованный агент IATA",
        iata_desc: "Признан Международной ассоциацией воздушного транспорта за выдающиеся услуги и соответствие стандартам.",
        top_seller_title: "Лучший продавец 2024",
        top_seller_desc: "Отмечен ведущими авиакомпаниями за выдающиеся продажи билетов и удовлетворенность клиентов.",
        global_member_title: "Участник глобальной сети",
        global_member_desc: "Часть всемирной сети доверенных туристических агентств, гарантирующих качество и надежность.",
        why_book: "Почему бронировать через SpeedAir?",
        why_book_desc: "Наслаждайтесь простым бронированием с мгновенным подтверждением, гибкими опциями и эксклюзивными предложениями. Наша платформа создана для вашего удобства: сравнивайте рейсы, управляйте бронированиями и получайте поддержку в любое время. SpeedAir гарантирует лучшее качество и сервис на каждом этапе.",
        agents: "Профессиональные агенты",
        agents_desc: "Наша команда экспертов всегда готова помочь вам с персонализированным сервисом и советами.",
        customers: "Довольные клиенты",
        customers_desc: "Миллионы путешественников доверяют SpeedAir благодаря нашему стремлению к качеству и надежности.",
        years: "Лет опыта",
        years_desc: "Мы предоставляем качественные решения для путешествий и строим долгосрочные отношения с 2021 года.",
        certificates_title: "Наши сертификаты и достижения",
        benefits_title: "Наши преимущества и особенности",
        best_price: "Лучшие цены",
        best_price_desc: "Мы постоянно отслеживаем тарифы, чтобы предложить вам самые низкие цены и эксклюзивные скидки на авиабилеты по всему миру.",
        live_support: "Круглосуточная поддержка",
        live_support_desc: "Наша служба поддержки доступна 24/7 и поможет вам с бронированием, изменениями и любыми вопросами о путешествиях.",
        reliable_safe: "Надежно и безопасно",
        reliable_safe_desc: "Ваша безопасность и конфиденциальность — наш приоритет. Мы используем современные технологии и сотрудничаем только с проверенными авиакомпаниями.",
        contact_us: "Связаться с нами",
        contact_us_desc: "Если у вас есть вопросы о наших услугах, нужна поддержка или вы хотите оставить отзыв, наша команда всегда готова помочь вам.",
        email: "Электронная почта",
        website: "Веб-сайт",
        phone: "Телефон",
        location: "Адрес",
        get_in_touch: "Свяжитесь с нами.",
        your_name: "Ваше имя",
        email_address: "Электронная почта",
        phone_number: "Телефон",
        message: "Сообщение",
        submit: "Отправить",
        roundtrip: "Туда-обратно",
        oneway: "В одну сторону",
        depart_from: "Откуда",
        arrive_at: "Куда",
        traveller_toggle: "1 взрослый, эконом",
        search: "Поиск",
        adult: "Взрослый 12+",
        child: "Ребенок 2-11",
        infant: "Младенец 0-1",
        swap: "Поменять",
        decrease: "Уменьшить",
        increase: "Увеличить",
        footer: "© 2024 SpeedAir Туристическое агентство. Все права защищены.",
        who_is_speedair: "Что такое SpeedAir",
        who_is_speedair_text: "SpeedAir — ведущая туристическая компания, посвящённая тому, чтобы сделать ваши путешествия легкими, запоминающимися и доступными. С многолетним опытом в индустрии наши специалисты предоставляют индивидуальные решения для частных лиц, семей и бизнеса.",
        our_mission: "Наша миссия",
        our_mission_text: "Вдохновлять и помогать людям открывать мир, предлагая исключительные путешествия, отличный сервис и лучшие цены.",
        our_values: "Наши ценности",
        customer_focus: "Ориентация на клиента",
        customer_focus_text: "Мы ставим ваши потребности на первое место, подбирая поездки под ваши предпочтения.",
        reliability: "Надежность",
        reliability_text: "Прозрачное бронирование и поддержка на каждом этапе.",
        expertise: "Экспертность",
        expertise_text: "Наши опытные агенты дадут лучшие советы и предложения по всему миру.",
        why_choose: "Почему выбирают SpeedAir?",
        li1: "Широкий выбор направлений по всему миру",
        li2: "Индивидуальные турпакеты",
        li3: "Круглосуточная поддержка",
        li4: "Выгодные цены и эксклюзивные предложения",
        li5: "Доверие тысяч довольных путешественников",
        our_locations: "Наши офисы",
        address: "Адрес",
        services_title: "Наши услуги",
        flight_bookings: "Бронирование авиабилетов",
        flight_bookings_desc: "Бронируйте внутренние и международные рейсы по лучшим ценам и с гибкими условиями.",
        hotel_reservations: "Бронирование отелей",
        hotel_reservations_desc: "Выбирайте из широкого ассортимента отелей и размещений под любые нужды и бюджет.",
        car_rentals: "Аренда автомобилей",
        car_rentals_desc: "Арендуйте автомобили в пункте назначения для удобства и комфорта во время поездки.",
        travel_packages: "Туристические пакеты",
        travel_packages_desc: "Наслаждайтесь индивидуальными турами для семей, пар и самостоятельных путешественников.",
        travel_insurance: "Страхование путешествий",
        travel_insurance_desc: "Путешествуйте спокойно с нашими комплексными страховыми решениями.",
        support_247: "Поддержка 24/7",
        support_247_desc: "Наша команда всегда на связи, чтобы помочь вам до, во время и после поездки.",
        need_special: "Нужно что-то особенное?",
        ready_adventure: "Готовы спланировать свое следующее путешествие?",
        why_choose: "Почему выбирают SpeedAir?",
        customer_say: "Что говорят наши клиенты",
        review_1: "SpeedAir сделал наш медовый месяц незабываемым! Процесс бронирования прошёл гладко, а персонал всегда был готов помочь. Очень рекомендую!",
        review_2: "Я переживал по поводу поездки за границу, но SpeedAir обо всём позаботился. Я чувствовал себя в безопасности и получил поддержку на каждом этапе.",
        review_3: "Отличный сервис и отличное соотношение цены и качества. Обязательно забронирую следующую поездку через SpeedAir!",
        review_4: "Профессионально, надёжно и дружелюбно. SpeedAir превзошёл все мои ожидания!",
        leave_review_heading: "Хотите поделиться своим опытом?",
        leave_review_text: "Мы ценим ваш отзыв! Нажмите ниже, чтобы оставить отзыв или связаться с нами.",
        leave_review_button: "Оставить отзыв / Связаться с нами",
        contact_us: "Связаться с нами",
        contact_text: "Если у вас есть вопросы, нужна поддержка или вы хотите оставить отзыв, наша команда всегда готова помочь.",
        email: "Эл. почта",
        website: "Веб-сайт",
        phone: "Телефон",
        location: "Адрес",
        get_in_touch: "Свяжитесь с нами.",
        your_name: "Ваше имя",
        email_address: "Эл. почта",
        phone_number: "Телефон",
        message: "Сообщение",
        submit: "Отправить",
        footer_text: "© 2025 SpeedAir. Все права защищены."
    },
    uz: {
        title: "SpeedAir - Sizning ishonchli sayohat hamkoringiz",
        brand: "SpeedAir",
        about_us_nav: "Biz haqimizda",
        services_nav: "Xizmatlar",
        reviews_nav: "Sharhlar",
        contact_nav: "Aloqa va yordam",
        welcome: "SpeedAirga xush kelibsiz",
        welcome_sub: "Sizning sayohatingiz biz bilan boshlanadi",
        iata_title: "IATA akkreditatsiyalangan agent",
        iata_desc: "Xalqaro havo transporti assotsiatsiyasi tomonidan xizmat sifati va standartlarga muvofiqligi uchun tan olingan.",
        top_seller_title: "2024-yilning eng yaxshi sotuvchisi",
        top_seller_desc: "Yetakchi aviakompaniyalar tomonidan yuqori savdo va mijozlar mamnunligi uchun taqdirlangan.",
        global_member_title: "Global sayohat tarmog‘i a’zosi",
        global_member_desc: "Ishonchli agentliklar tarmog‘ining bir qismi sifatida sifat va ishonchlilikni kafolatlaymiz.",
        why_book: "Nima uchun SpeedAir orqali bron qilish kerak?",
        why_book_desc: "Tez va qulay bron qilish, moslashuvchan imkoniyatlar va siz uchun maxsus takliflar. Platformamiz orqali reyslarni solishtiring, buyurtmalaringizni boshqaring va istalgan vaqtda yordam oling. SpeedAir har bir bosqichda eng yaxshi qiymat va xizmatni kafolatlaydi.",
        agents: "Professional agentlar",
        agents_desc: "Bizning tajribali jamoamiz sizga har doim shaxsiy yondashuv va maslahatlar bilan yordam beradi.",
        customers: "Baxtli mijozlar",
        customers_desc: "Millionlab sayohatchilar SpeedAir’ga ishonishadi, chunki biz sifat va ishonchlilikka sodiqmiz.",
        years: "Yillik tajriba",
        years_desc: "2021-yildan buyon sifatli sayohat yechimlari va mustahkam hamkorliklar.",
        certificates_title: "Sertifikatlar va yutuqlarimiz",
        benefits_title: "Afzalliklar va imkoniyatlar",
        best_price: "Eng yaxshi narxlar",
        best_price_desc: "Biz doimiy ravishda tariflarni kuzatib boramiz va sizga eng past narxlar hamda eksklyuziv chegirmalarni taqdim etamiz.",
        live_support: "24/7 yordam",
        live_support_desc: "Bizning yordam jamoamiz sizga har doim, kunu tun, bron qilish, o‘zgartirish va boshqa savollaringiz bo‘yicha yordam beradi.",
        reliable_safe: "Ishonchli va xavfsiz",
        reliable_safe_desc: "Sizning xavfsizligingiz va maxfiyligingiz biz uchun muhim. Biz zamonaviy texnologiyalardan foydalanamiz va faqat ishonchli aviakompaniyalar bilan hamkorlik qilamiz.",
        contact_us: "Biz bilan bog'laning",
        contact_us_desc: "Agar sizda savollar bo‘lsa, yordam kerak bo‘lsa yoki fikr-mulohazalaringizni bildirmoqchi bo‘lsangiz, bizning jamoamiz har doim yordam berishga tayyor.",
        email: "Email",
        website: "Veb-sayt",
        phone: "Telefon",
        location: "Manzil",
        get_in_touch: "Bog'laning.",
        your_name: "Ismingiz",
        email_address: "Email manzili",
        phone_number: "Telefon raqami",
        message: "Xabar",
        submit: "Yuborish",
        roundtrip: "Qaytish bilan",
        oneway: "Bir tomonga",
        depart_from: "Qayerdan",
        arrive_at: "Qayerga",
        traveller_toggle: "1 kattalar, iqtisodiy",
        search: "Qidirish",
        adult: "Katta 12+",
        child: "Bola 2-11",
        infant: "Go'dak 0-1",
        swap: "Almashtirish",
        decrease: "Kamaytirish",
        increase: "Ko'paytirish",
        footer: "© 2024 SpeedAir sayohat agentligi. Barcha huquqlar himoyalangan.",
        who_is_speedair: "SpeedAir haqida",
        who_is_speedair_text: "SpeedAir — sizning sayohatlaringizni oson, unutilmas va arzon qilishga bag‘ishlangan yetakchi sayohat agentligi. Ko‘p yillik tajribaga ega jamoamiz har bir mijoz uchun individual yechimlarni taklif qiladi.",
        our_mission: "Bizning vazifamiz",
        our_mission_text: "Odamlarni dunyoni kashf etishga ilhomlantirish va yordam berish — ajoyib sayohatlar, yuqori darajadagi xizmat va eng yaxshi narxlar bilan.",
        our_values: "Bizning qadriyatlarimiz",
        customer_focus: "Mijozga yo‘naltirilganlik",
        customer_focus_text: "Sizning ehtiyojlaringiz biz uchun birinchi o‘rinda — har bir safar sizga moslashtiriladi.",
        reliability: "Ishonchlilik",
        reliability_text: "Har bir bosqichda shaffof va oson bron qilish hamda yordam.",
        expertise: "Mutaxassislik",
        expertise_text: "Tajribali agentlarimiz eng yaxshi maslahat va takliflarni beradi.",
        why_choose: "Nega aynan SpeedAir?",
        li1: "Ichki va xalqaro yo‘nalishlarning keng tanlovi",
        li2: "Moslashtirilgan sayohat paketlari",
        li3: "24/7 mijozlarni qo‘llab-quvvatlash",
        li4: "Raqobatbardosh narxlar va eksklyuziv takliflar",
        li5: "Minglab baxtli mijozlar ishonchi",
        our_locations: "Bizning manzillarimiz",
        address: "Manzil",
        services_title: "Bizning xizmatlarimiz",
        flight_bookings: "Aviabiletlar bron qilish",
        flight_bookings_desc: "Ichki va xalqaro reyslarni eng yaxshi narxlar va moslashuvchan imkoniyatlar bilan bron qiling.",
        hotel_reservations: "Mehmonxonalarni bron qilish",
        hotel_reservations_desc: "Turli ehtiyoj va byudjet uchun keng turdagi mehmonxonalar va joylarni tanlang.",
        car_rentals: "Avtomobil ijarasi",
        car_rentals_desc: "Sayohatingiz davomida qulaylik va komfort uchun manzilingizda avtomobil ijaraga oling.",
        travel_packages: "Sayohat paketlari",
        travel_packages_desc: "Oila, juftliklar va yakka sayohatchilar uchun moslashtirilgan sayohat paketlaridan bahramand bo‘ling.",
        travel_insurance: "Sayohat sug‘urtasi",
        travel_insurance_desc: "Bizning to‘liq sug‘urta variantlarimiz bilan xotirjam sayohat qiling.",
        support_247: "24/7 qo‘llab-quvvatlash",
        support_247_desc: "Jamoamiz safaringizdan oldin, davomida va keyin sizga yordam berishga doim tayyor.",
        need_special: "Maxsus ehtiyojlaringiz bormi?",
        ready_adventure: "Keyingi sayohatingizni rejalashtirishga tayyormisiz?",
        why_choose: "Nega aynan SpeedAir?",
        customer_say: "Mijozlarimiz nima deydi",
        review_1: "SpeedAir asal oyimizni unutilmas qildi! Buyurtma jarayoni juda oson bo‘ldi va xodimlar doimo yordamga tayyor edi. Tavsiya qilaman!",
        review_2: "Chet elga sayohat qilishdan xavotirda edim, lekin SpeedAir hammasini o‘zi hal qildi. O‘zimni xavfsiz va qo‘llab-quvvatlangan his qildim.",
        review_3: "Ajoyib xizmat va arzon narx. Keyingi sayohatimni albatta SpeedAir orqali bron qilaman!",
        review_4: "Professional, ishonchli va samimiy. SpeedAir barcha kutganimdan oshdi!",
        leave_review_heading: "Tajribangizni baham ko'rmoqchimisiz?",
        leave_review_text: "Fikringiz biz uchun muhim! Quyidagi tugmani bosib sharh qoldiring yoki biz bilan bog'laning.",
        leave_review_button: "Sharh qoldirish / Bog‘lanish",
        contact_us: "Biz bilan bog'laning",
        contact_text: "Agar sizda savollar bo‘lsa, yordam kerak bo‘lsa yoki fikr bildirmoqchi bo‘lsangiz – jamoamiz har doim sizga yordam beradi.",
        email: "Email",
        website: "Veb-sayt",
        phone: "Telefon",
        location: "Manzil",
        get_in_touch: "Biz bilan bog‘laning.",
        your_name: "Ismingiz",
        email_address: "Email manzilingiz",
        phone_number: "Telefon raqamingiz",
        message: "Xabar",
        submit: "Yuborish",
        footer_text: "© 2025 SpeedAir Travel Agency. Barcha huquqlar himoyalangan."
    }
};

function setLanguage(lang) {
    document.querySelectorAll('[data-i18n]').forEach(el => {
        const key = el.getAttribute('data-i18n');
        if (translations[lang] && translations[lang][key]) {
            el.textContent = translations[lang][key];
        }
    });
    // Update language label
    document.getElementById('lang-label').textContent =
        lang === 'en' ? 'En' : lang === 'ru' ? 'Ру' : "Uz";
    document.documentElement.lang = lang;
    localStorage.setItem('lang', lang);
}

document.getElementById('lang-btn').onclick = function (e) {
    e.stopPropagation();
    document.getElementById('lang-list').hidden = !document.getElementById('lang-list').hidden;
};
document.querySelectorAll('#lang-list li').forEach(li => {
    li.onclick = function (e) {
        setLanguage(this.getAttribute('data-lang'));
        document.getElementById('lang-list').hidden = true;
    };
});
document.addEventListener('click', function (e) {
    if (!e.target.closest('.lang-switcher')) {
        document.getElementById('lang-list').hidden = true;
    }
});

// On page load, set language from localStorage or default to EN
const savedLang = localStorage.getItem('lang') || 'en';
setLanguage(savedLang);